language: node_js
node_js:
  - '14' # 或你需要的 Node.js 版本

# 安装依赖
install:
  - npm install

# 执行测试
script:
  - npm test

# 部署配置
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master # 或者 master， 取决于你使用的主要分支名称

# 通常情况下，这个选项可以用于开启或关闭 Travis CI 的安全特性
branches:
  only:git
    - master # 确保只对master 分支执行部署
