name: Publish npm Package Wain

on:
  push:
    branches:
      - master  # 设置为你的主要分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Build
      run: npm run build  # 如果你有构建步骤

    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish
